#1 Sprint 1
Galyk-Ilya/java-filmorate pull request #1
Opened 2023-02-23 08:18 UTC by Galyk-Ilya

Сконфигурированно Spring приложение
Разработано 2 REST-контроллера, /films & /users
Проработана валидация согласно ТЗ

2023-02-23 19:07 UTC, kalitva requested changes

2023-02-23 19:07 UTC, kalitva commented on pom.xml
> +            <groupId>junit</groupId>
junit зависимости уже есть в spring-boot-stater-test, удали

2023-02-23 19:07 UTC, kalitva commented on pom.xml
> +        <relativePath/> <!-- lookup parent from repository -->
Удали коммент

2023-02-23 19:07 UTC, kalitva commented on pom.xml
> +            <artifactId>gson</artifactId>
gson нам не пригодится

2023-02-23 19:07 UTC, kalitva commented on pom.xml
> +            <artifactId>jackson-databind</artifactId>
jackson уже есть в spring-boot-starter-web

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Замени табы на пробелы. В intellij нажми Edit --> Convert Indents --> To spaces

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/Controller.java
> +    Integer counter = 0;
private int

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/Controller.java
> +
Удали лишние пустые строки

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/Controller.java
> +import java.util.*;
Не используй wildcard импорты.

https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

Это может служить причиной лишних конфликтов при мерже веток. Настрой intellij чтобы она не схлопывала импорты

https://blog.marcnuri.com/intellij-idea-how-to-disable-wildcard-imports

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/Controller.java
> +    public abstract void validate(T data, boolean isCreate);
Не используй флаги в параметрах методов или конструкторов, вообще никогда не используй

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Collection<Film> getAll() {
Не надо переопределять этот метод, просто поставь `@GetMapping` над super реализацией (так как определен префикс в  `RequestMapping`, вызовы будут поступать в нужный контроллер)

То же самое для двух методов ниже

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (isCreate) {
При создании просто засетишь новое айди, не надо это проверять

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            if (!dataMap.containsKey(film.getId())) {
Перенеси в `Controller#update`

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +                throw new InputDataException("Невозможно добавить " + film.getName() + ", так как он был добавлен ранее");
Сообщение в исключение - только по английски

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            log.debug("film " + film.getName() + " id" + film.getId() + " изменен");
Логирование - по английски

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Map<Integer, Film> getFilmMap() {
Зачем здесь этот метод? Удали, в контроллере не должно быть публичных методов без маппинга

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public void validate(User user, boolean isCreate) {
Пожалуйста, пустая линия между объявлениями методов

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +}
Все те же замечания, что и для `FilmController`

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/GlobalException.java
> +//    @ExceptionHandler
Удали закомментированный код, если вдруг понадобится, достанешь из vcs

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        //Долго не мог обойти ошибку json-a на вход LocalDate поля, так и не нашел решение =\
Попробуй так

```
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate releaseDate;
```

2023-02-23 19:07 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +package ru.yandex.practicum.filmorate;
Давай удалим этот файл

2023-02-23 19:07 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +        String description200 = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111" +
`String description200 = "1".repeat(200)`

2023-02-23 19:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorObject.java
> +public class ErrorObject {
`ErrorObject --> ErrorResponse`

2023-02-24 21:22 UTC, Galyk-Ilya commented
Долго решал проблему с конфликтом тестов в Idea и Git-а
При аннотировании модели аннотациями: @NoArgsConstructor(force = true), @AllArgsConstructor
создавая объекты, для Unit-тестов, через new, недоступно поле родителя (id) в параметрах конструктора создаваемого наследника (нашел решение правками каждого объекта через сеттер). Но при этом, создавая явный избыточный конструктор в дополнении к созданным аннотацией, GitHub-тесты просто не видели этот конструктор, почему?

2023-02-25 09:49 UTC, kalitva requested changes

2023-02-25 09:49 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/Controller.java
> +    protected final HashMap<Integer, T> dataMap = new HashMap<>();
`dataMap --> entities`

Избегай в названиях коллекций (и методов соответственно) слова типа `List Map Set Array` и.т.п

2023-02-25 09:49 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/Controller.java
> +    public T create(T data) {
Лучше `data --> entity`

2023-02-25 09:49 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Collection<Film> getAll() {
Вообще не надо переопределять, также удали `create` и `update`, здесь должен остаться только `validate`. Логирование можешь перенести в родителя

2023-02-25 09:49 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    protected String name;
А почему protected?

2023-02-25 09:49 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/Controller.java
> +    public abstract void validate(T data);
Думаю, лучше сделать метод не абстрактным, а просто пустым с возможность переопределить. Могут появиться новые контроллеры, где валидация не требуется

2023-02-25 09:49 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@ToString
Если нужно, чтобы айдишник тоже был в `toString` - `@ToString(callSuper = true)`

2023-02-25 09:49 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@EqualsAndHashCode
`callSuper = true`, если нужно чтобы айдишник участвовал в equals и hashCode

2023-02-26 08:17 UTC, kalitva commented
> Долго решал проблему с конфликтом тестов в Idea и Git-а При аннотировании модели аннотациями: @NoArgsConstructor(force = true), @AllArgsConstructor создавая объекты, для Unit-тестов, через new, недоступно поле родителя (id) в параметрах конструктора создаваемого наследника (нашел решение правками каждого объекта через сеттер). Но при этом, создавая явный избыточный конструктор в дополнении к созданным аннотацией, GitHub-тесты просто не видели этот конструктор, почему?

Не знаю в чем дело, ломбок и наследование это всегда геморно. Я бы вообще отказался от любых аннотаций для конструкторов. Зачем они нужны? В продакшен коде конструкторы не используется, для тестов можно создание объекта вынести в метод, а в методе сеттерами наполнить объект

2023-02-26 08:34 UTC, kalitva approved these changes

2023-02-26 08:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/Controller.java
> +    public void validate(T entity){}
protected

2023-02-26 08:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final LocalDate theBirthOfCinema = LocalDate.of(1895, 12, 28);
Оформи константу по конвенции - статическое поле, название в upper case

`private static final LocalDate CINEMA_BIRTHDAY = LocalDate.of(1895, 12, 28);`

https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2023-02-26 08:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.debug(film.getName() + " passed the checks of all fields");
Думаю, это логирование можно убрать

2023-02-26 08:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (user.getBirthday().isAfter(LocalDate.now())) {
Можно воспользоваться аннотацией `@javax.validation.constraints.Past`

2023-02-26 08:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Все-таки это не совсем валидация. Я бы предложил вынести в другой метод, назвать например `preSave`. Должно также работать как и с `validate` - пустой метод определяется в родителе, там же вызывается перед сохранением/обновлением. В этом контроллере нужно будет переопределить

2023-02-26 08:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank(message = "Movie title cannot be empty")
Давай отделим пустыми линиями поля с аннотациями

2023-02-26 08:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Model.java
> +    @NotNull
Примитив не может быть null

2023-02-26 08:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Min(value = 1, message = "Movie duration must be positive")
Лучше - `@Positive`

2023-02-26 08:34 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +public class FilmControllerTest {
Если интересно как правильно тестировать спринговые контроллеры, напиши в чате, отправлю пример

2023-02-26 13:13 UTC, merged